[package]
name = "zed_puter"
version = "0.1.1"
edition = "2021"
publish = false
license = "MIT"

[lib]
path = "src/puter.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
serde = "1.0"
schemars = "0.8"
